### ISSUE TITLE
Add support for more Just Dance versions

### ISSUE THREAD

**Issue by MrKev312** [MrKev312/JustDanceEditor#2]

**Comment by MrKev312** [comment]
Currently should support all Switch, most PC, most WIIU games

**Comment by MrKev312** [comment]
Added support for Wii 2016-2020 in jdi rewrite branch

**Comment by Forusim** [comment]
I am trying to extract .ipk bundles from a Just Dance 2019 Playstation 4 game, but it seem to have a different compression method.
Some files can be opened, like fire.ogg but the fire.hd.webm is invalid video file (tested with MPC-BE and mpv players).
Here is the log:
```
Extracting 'fire_orbis.ipk' to 'R:\CUSA12549\fire_orbis'...
IPK version: 5
Number of files: 269
File: fire.hd.mpd.ckd
File: fire.wav.ckd
File: amb_fire_intro.wav.ckd
File: amb_fire_outro.wav.ckd
File: fire_bull1_p1.gesture
File: fire_bull1_p2.gesture
File: fire_bull2_p1.gesture
File: fire_bull2_p2.gesture
File: fire_bullet1_p1.gesture
File: fire_bullet1_p2.gesture
File: fire_bullet2_p1.gesture
File: fire_bullet2_p2.gesture
File: fire_bullet2p1.msm
File: fire_bullet2p2.msm
File: fire_bulletp1.msm
File: fire_bulletp1_end.gesture
File: fire_bulletp1_strt.gesture
File: fire_bulletp2.msm
File: fire_bulletp2_end.gesture
File: fire_bulletp2_strt.gesture
File: fire_bullp1_end.gesture
File: fire_bullp1_strt.gesture
File: fire_bullp2_end.gesture
File: fire_bullp2_strt.gesture
File: fire_cazyp1.gesture
File: fire_cazyp1.msm
File: fire_check1_p1.gesture
File: fire_check1_p2.gesture
File: fire_check1p1.msm
File: fire_check1p2.msm
File: fire_check_p1.gesture
File: fire_check_p2.gesture
File: fire_closing1.msm
File: fire_closing2.msm
File: fire_closingp1_end.gesture
File: fire_closingp1_strt.gesture
File: fire_closingp2_end.gesture
File: fire_closingp2_strt.gesture
File: fire_crazyp2.gesture
File: fire_crazyp2.msm
File: fire_falling.msm
File: fire_falling_end_p1.gesture
File: fire_falling_end_p2.gesture
File: fire_falling_l_end_p1.gesture
File: fire_falling_l_end_p2.gesture
File: fire_falling_l_strt_p1.gesture
File: fire_falling_l_strt_p2.gesture
File: fire_falling_r_strt_p1.gesture
File: fire_falling_r_strt_p2.gesture
File: fire_falling_strt_p1.gesture
File: fire_falling_strt_p2.gesture
File: fire_fight1.msm
File: fire_fight1p2.gesture
File: fire_fight1p2.msm
File: fire_fight2.msm
File: fire_fightp1.gesture
File: fire_fightp2.gesture
File: fire_fire.msm
File: fire_first_l.gesture
File: fire_first_r.gesture
File: fire_first_strt.gesture
File: fire_first_strt1.gesture
File: fire_firststair.msm
File: fire_fly.msm
File: fire_fly_p1.gesture
File: fire_fly_p2.gesture
File: fire_get_p1_end.gesture
File: fire_get_p1_strt.gesture
File: fire_get_p1_strt1.gesture
File: fire_get_p1_strt2.gesture
File: fire_get_p1_strt3.gesture
File: fire_get_p2_end.gesture
File: fire_get_p2_strt.gesture
File: fire_get_p2_strt1.gesture
File: fire_get_p2_strt2.gesture
File: fire_get_p2_strt3.gesture
File: fire_gethat.msm
File: fire_kame_p1_end.gesture
File: fire_kame_p1_strt.gesture
File: fire_kamehameha.msm
File: fire_kamehameha2.msm
File: fire_mime.msm
File: fire_mime1_p2.gesture
File: fire_mime2.msm
File: fire_mime2_p2.gesture
File: fire_mime3.msm
File: fire_mime_p2.gesture
File: fire_ninja.msm
File: fire_ninja_p1.gesture
File: fire_ninja_p2.gesture
File: fire_oh_p1.gesture
File: fire_oh_p2.gesture
File: fire_ohfriend.msm
File: fire_p1_idota1_end.gesture
File: fire_p1_idota1_strt.gesture
File: fire_p1_idota2_strt.gesture
File: fire_p1_idota_end.gesture
File: fire_p1_idota_strt.gesture
File: fire_p1_idota_strt1.gesture
File: fire_p2_idota1_end.gesture
File: fire_p2_idota1_strt.gesture
File: fire_p2_idota2_strt.gesture
File: fire_p2_idota_end.gesture
File: fire_p2_idota_strt.gesture
File: fire_p2_idota_strt1.gesture
File: fire_pointing.msm
File: fire_pointing_p1.gesture
File: fire_pointing_p2.gesture
File: fire_pointingp2.msm
File: fire_preparep1.gesture
File: fire_punchup.msm
File: fire_punchup_end.gesture
File: fire_punchup_l.gesture
File: fire_punchup_r.gesture
File: fire_push_p2.gesture
File: fire_pushedback2.msm
File: fire_pushedp2.gesture
File: fire_ridge.gesture
File: fire_robot1.msm
File: fire_robot1_p1.gesture
File: fire_robot2.msm
File: fire_robot_p1.gesture
File: fire_robotback.msm
File: fire_robotback_p1.gesture
File: fire_shi_p1_end.gesture
File: fire_shi_p1_strt.gesture
File: fire_shi_p1_strt1.gesture
File: fire_shi_p2_end.gesture
File: fire_shi_p2_strt.gesture
File: fire_shi_p2_strt1.gesture
File: fire_shifumi1.msm
File: fire_shifumi2.msm
File: fire_slice.msm
File: fire_slice_l.gesture
File: fire_slice_r.gesture
File: fire_slice_strt.gesture
File: fire_slice_strt1.gesture
File: fire_slowback1_p1.gesture
File: fire_slowback1_p2.gesture
File: fire_slowback2_p1.gesture
File: fire_slowback_p1.gesture
File: fire_slowback_p11.gesture
File: fire_slowback_p2.gesture
File: fire_slowgetback.msm
File: fire_slowkame1_p1.gesture
File: fire_slowkameha.msm
File: fire_slowkameha_p1.gesture
File: fire_slowpush.msm
File: fire_slowpush1_p2.gesture
File: fire_slowpush_p2.gesture
File: fire_slowpush_p21.gesture
File: fire_swag.gesture
File: fire_wind.msm
File: fire_wind1.gesture
File: fire_wind1_p1.gesture
File: fire_wind1_p2.gesture
File: fire_wind_end.gesture
File: fire_wind_p1.gesture
File: fire_wind_p1_strt.gesture
File: fire_wind_p1_strt1.gesture
File: fire_wind_p2.gesture
File: fire_wind_p2_strt.gesture
File: fire_wind_p2_strt1.gesture
File: fire_wind_strt.gesture
File: fire_wola.msm
File: fire_wola_p1.gesture
File: fire_wola_p2.gesture
File: fire_wutp1.gesture
File: fire_wutp2.gesture
File: fire_bullet2p1.msm
File: fire_bullet2p2.msm
File: fire_bulletp1.msm
File: fire_bulletp2.msm
File: fire_cazyp1.msm
File: fire_check1p1.msm
File: fire_check1p2.msm
File: fire_closing1.msm
File: fire_closing2.msm
File: fire_crazyp2.msm
File: fire_falling.msm
File: fire_fight1.msm
File: fire_fight1p2.msm
File: fire_fight2.msm
File: fire_fire.msm
File: fire_firststair.msm
File: fire_fly.msm
File: fire_gethat.msm
File: fire_kamehameha.msm
File: fire_kamehameha2.msm
File: fire_mime.msm
File: fire_mime2.msm
File: fire_mime3.msm
File: fire_ninja.msm
File: fire_ohfriend.msm
File: fire_pointing.msm
File: fire_pointingp2.msm
File: fire_punchup.msm
File: fire_pushedback2.msm
File: fire_robot1.msm
File: fire_robot2.msm
File: fire_robotback.msm
File: fire_shifumi1.msm
File: fire_shifumi2.msm
File: fire_slice.msm
File: fire_slowgetback.msm
File: fire_slowkameha.msm
File: fire_slowpush.msm
File: fire_wind.msm
File: fire_wola.msm
File: fire.ogg
File: fire.hd.webm
Compression: 104696, File: fire_banner_bkg.tga.ckd
Compression: 87778, File: fire_coach_1.tga.ckd
Compression: 73930, File: fire_coach_2.tga.ckd
Compression: 128423, File: fire_cover_albumcoach.tga.ckd
Compression: 22438, File: fire_cover_online_kids.tga.ckd

An error occurred during extraction: The archive entry was compressed using an unsupported compression method.
2026-04-09 21:37:16 | IPK Extraction failed for R:\Just Dance 2019 [CUSA12549]\fire_orbis.ipk: The archive entry was compressed using an unsupported compression method.
```

**Comment by MrKev312** [comment]
JDI-rewrite branch update:
Added support for PS3/PS4/PS5, X360/XboxOne/XboxSeries
JD2014/JD2015 importing quality ranges from near-perfect to fully broken for realtime rendered maps
Exporting/importing works to JD2014-JD2023+

Question now is whether to keep going with JD1-4 or not, given they run on a different engine with different formats, I'm leaning towards no.

@Forusim unpacking a JD2022 PS4 IPK works on the latest commit in JDI-Rewrite, does your 2019 IPK still fail with that?

**Comment by Forusim** [comment]
@MrKev312 Thanks for the hint. I have compiled the latest code from the suggested branch, but the result is kind of same:

<details>
Developed by: MrKev312
13:56:57 info: JustDanceEditor.Cli.Interactive.ConsoleApp[0]
      Starting ConsoleApp
Version: 2.3.0
Current Directory: D:\Code\JustDanceEditor\JustDanceEditor.Cli\bin\Release\net10.0


================ Main Menu ================
Please select an action:
0)  Exit Program
1)  Convert Between Formats
2)  Batch Convert All Songs in a Folder
3)  Tools
Please select an option (between 0 and 3): 3
=========================================

--- Tools ---
Select a tool provider
0)  IPK
1)  Unity
Please select an option (between 0 and 1): 0
Select a tool
0)  Extract Archive
1)  Pack Archive
Please select an option (between 0 and 1): 0
Extract Archive
Enter the IPK archive path (This file must already exist)
You can also drag and drop the file onto the console window and press Enter.
File path: "R:\Just Dance 2019 [CUSA12549]\fire_orbis.ipk"
Enter the output folder (This folder will be created if it doesn't exist)
You can also drag and drop the folder onto the console window and press Enter.
Folder path: R:\CUSA12549\fire_orbis
14:10:40 info: JustDanceEditor.AppHost.IpkToolProvider[0]
      Extracting IPK archive 'R:\Just Dance 2019 [CUSA12549]\fire_orbis.ipk' into 'R:\CUSA12549\fire_orbis'
IPK version: 5
Number of files: 269
File: fire.hd.mpd.ckd
File: fire.wav.ckd
File: amb_fire_intro.wav.ckd
File: amb_fire_outro.wav.ckd
File: fire_bull1_p1.gesture
File: fire_bull1_p2.gesture
File: fire_bull2_p1.gesture
File: fire_bull2_p2.gesture
File: fire_bullet1_p1.gesture
File: fire_bullet1_p2.gesture
File: fire_bullet2_p1.gesture
File: fire_bullet2_p2.gesture
File: fire_bullet2p1.msm
File: fire_bullet2p2.msm
File: fire_bulletp1.msm
File: fire_bulletp1_end.gesture
File: fire_bulletp1_strt.gesture
File: fire_bulletp2.msm
File: fire_bulletp2_end.gesture
File: fire_bulletp2_strt.gesture
File: fire_bullp1_end.gesture
File: fire_bullp1_strt.gesture
File: fire_bullp2_end.gesture
File: fire_bullp2_strt.gesture
File: fire_cazyp1.gesture
File: fire_cazyp1.msm
File: fire_check1_p1.gesture
File: fire_check1_p2.gesture
File: fire_check1p1.msm
File: fire_check1p2.msm
File: fire_check_p1.gesture
File: fire_check_p2.gesture
File: fire_closing1.msm
File: fire_closing2.msm
File: fire_closingp1_end.gesture
File: fire_closingp1_strt.gesture
File: fire_closingp2_end.gesture
File: fire_closingp2_strt.gesture
File: fire_crazyp2.gesture
File: fire_crazyp2.msm
File: fire_falling.msm
File: fire_falling_end_p1.gesture
File: fire_falling_end_p2.gesture
File: fire_falling_l_end_p1.gesture
File: fire_falling_l_end_p2.gesture
File: fire_falling_l_strt_p1.gesture
File: fire_falling_l_strt_p2.gesture
File: fire_falling_r_strt_p1.gesture
File: fire_falling_r_strt_p2.gesture
File: fire_falling_strt_p1.gesture
File: fire_falling_strt_p2.gesture
File: fire_fight1.msm
File: fire_fight1p2.gesture
File: fire_fight1p2.msm
File: fire_fight2.msm
File: fire_fightp1.gesture
File: fire_fightp2.gesture
File: fire_fire.msm
File: fire_first_l.gesture
File: fire_first_r.gesture
File: fire_first_strt.gesture
File: fire_first_strt1.gesture
File: fire_firststair.msm
File: fire_fly.msm
File: fire_fly_p1.gesture
File: fire_fly_p2.gesture
File: fire_get_p1_end.gesture
File: fire_get_p1_strt.gesture
File: fire_get_p1_strt1.gesture
File: fire_get_p1_strt2.gesture
File: fire_get_p1_strt3.gesture
File: fire_get_p2_end.gesture
File: fire_get_p2_strt.gesture
File: fire_get_p2_strt1.gesture
File: fire_get_p2_strt2.gesture
File: fire_get_p2_strt3.gesture
File: fire_gethat.msm
File: fire_kame_p1_end.gesture
File: fire_kame_p1_strt.gesture
File: fire_kamehameha.msm
File: fire_kamehameha2.msm
File: fire_mime.msm
File: fire_mime1_p2.gesture
File: fire_mime2.msm
File: fire_mime2_p2.gesture
File: fire_mime3.msm
File: fire_mime_p2.gesture
File: fire_ninja.msm
File: fire_ninja_p1.gesture
File: fire_ninja_p2.gesture
File: fire_oh_p1.gesture
File: fire_oh_p2.gesture
File: fire_ohfriend.msm
File: fire_p1_idota1_end.gesture
File: fire_p1_idota1_strt.gesture
File: fire_p1_idota2_strt.gesture
File: fire_p1_idota_end.gesture
File: fire_p1_idota_strt.gesture
File: fire_p1_idota_strt1.gesture
File: fire_p2_idota1_end.gesture
File: fire_p2_idota1_strt.gesture
File: fire_p2_idota2_strt.gesture
File: fire_p2_idota_end.gesture
File: fire_p2_idota_strt.gesture
File: fire_p2_idota_strt1.gesture
File: fire_pointing.msm
File: fire_pointing_p1.gesture
File: fire_pointing_p2.gesture
File: fire_pointingp2.msm
File: fire_preparep1.gesture
File: fire_punchup.msm
File: fire_punchup_end.gesture
File: fire_punchup_l.gesture
File: fire_punchup_r.gesture
File: fire_push_p2.gesture
File: fire_pushedback2.msm
File: fire_pushedp2.gesture
File: fire_ridge.gesture
File: fire_robot1.msm
File: fire_robot1_p1.gesture
File: fire_robot2.msm
File: fire_robot_p1.gesture
File: fire_robotback.msm
File: fire_robotback_p1.gesture
File: fire_shi_p1_end.gesture
File: fire_shi_p1_strt.gesture
File: fire_shi_p1_strt1.gesture
File: fire_shi_p2_end.gesture
File: fire_shi_p2_strt.gesture
File: fire_shi_p2_strt1.gesture
File: fire_shifumi1.msm
File: fire_shifumi2.msm
File: fire_slice.msm
File: fire_slice_l.gesture
File: fire_slice_r.gesture
File: fire_slice_strt.gesture
File: fire_slice_strt1.gesture
File: fire_slowback1_p1.gesture
File: fire_slowback1_p2.gesture
File: fire_slowback2_p1.gesture
File: fire_slowback_p1.gesture
File: fire_slowback_p11.gesture
File: fire_slowback_p2.gesture
File: fire_slowgetback.msm
File: fire_slowkame1_p1.gesture
File: fire_slowkameha.msm
File: fire_slowkameha_p1.gesture
File: fire_slowpush.msm
File: fire_slowpush1_p2.gesture
File: fire_slowpush_p2.gesture
File: fire_slowpush_p21.gesture
File: fire_swag.gesture
File: fire_wind.msm
File: fire_wind1.gesture
File: fire_wind1_p1.gesture
File: fire_wind1_p2.gesture
File: fire_wind_end.gesture
File: fire_wind_p1.gesture
File: fire_wind_p1_strt.gesture
File: fire_wind_p1_strt1.gesture
File: fire_wind_p2.gesture
File: fire_wind_p2_strt.gesture
File: fire_wind_p2_strt1.gesture
File: fire_wind_strt.gesture
File: fire_wola.msm
File: fire_wola_p1.gesture
File: fire_wola_p2.gesture
File: fire_wutp1.gesture
File: fire_wutp2.gesture
File: fire_bullet2p1.msm
File: fire_bullet2p2.msm
File: fire_bulletp1.msm
File: fire_bulletp2.msm
File: fire_cazyp1.msm
File: fire_check1p1.msm
File: fire_check1p2.msm
File: fire_closing1.msm
File: fire_closing2.msm
File: fire_crazyp2.msm
File: fire_falling.msm
File: fire_fight1.msm
File: fire_fight1p2.msm
File: fire_fight2.msm
File: fire_fire.msm
File: fire_firststair.msm
File: fire_fly.msm
File: fire_gethat.msm
File: fire_kamehameha.msm
File: fire_kamehameha2.msm
File: fire_mime.msm
File: fire_mime2.msm
File: fire_mime3.msm
File: fire_ninja.msm
File: fire_ohfriend.msm
File: fire_pointing.msm
File: fire_pointingp2.msm
File: fire_punchup.msm
File: fire_pushedback2.msm
File: fire_robot1.msm
File: fire_robot2.msm
File: fire_robotback.msm
File: fire_shifumi1.msm
File: fire_shifumi2.msm
File: fire_slice.msm
File: fire_slowgetback.msm
File: fire_slowkameha.msm
File: fire_slowpush.msm
File: fire_wind.msm
File: fire_wola.msm
File: fire.ogg
File: fire.hd.webm
Compression: 104696, File: fire_banner_bkg.tga.ckd
Compression: 87778, File: fire_coach_1.tga.ckd
Compression: 73930, File: fire_coach_2.tga.ckd
Compression: 128423, File: fire_cover_albumcoach.tga.ckd
Compression: 22438, File: fire_cover_online_kids.tga.ckd

Extract Archive failed: The archive entry was compressed using an unsupported compression method.

Press any key to return to the main menu...
14:10:42 fail: JustDanceEditor.Cli.Interactive.Converting.ToolDialogue[0]
      Tool 'ipk.extract' failed: The archive entry was compressed using an unsupported compression method.
      System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
         at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
         at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
         at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
         at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
         at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
         at KevInc.UbiArt.Ipk.Decompressor.Decompress(Byte[] data)
         at KevInc.UbiArt.Ipk.UbiArtIpkParser.ProcessFileEntry(FileEntry entry, Stream fileStream, String outputDirectory, Boolean pathsAreSwapped, Boolean ShowInfo)
         at KevInc.UbiArt.Ipk.UbiArtIpkParser.Parse(Boolean ShowInfo)
         at JustDanceEditor.AppHost.IpkToolProvider.Extract(ToolExecutionContext context) in D:\Code\JustDanceEditor\JustDanceEditor.AppHost\IpkToolProvider.cs:line 98
         at JustDanceEditor.AppHost.IpkToolProvider.ExecuteAsync(ToolExecutionContext context, CancellationToken cancellationToken) in D:\Code\JustDanceEditor\JustDanceEditor.AppHost\IpkToolProvider.cs:line 77
         at JustDanceEditor.Cli.Interactive.Converting.ToolDialogue.ExecuteTool(IToolProvider provider, ToolDefinition tool) in D:\Code\JustDanceEditor\JustDanceEditor.Cli\Interactive\Converting\ToolDialogue.cs:line 44
</details>

**Comment by MrKev312** [comment]
@Forusim finally managed to get my hands on JD2019 for PS4, however, `fire_orbis.ipk` extracts fine for me. I've heard that if you downloaded it through google drive, ipk files tend to get broken by google zipping them?

This means that the only partially supported platform remains the Xbox One, which to my knowledge does not have the ability to dump games yet.

**Comment by Forusim** [comment]
Thank you for looking into it. Does your fire_orbis.ipk has same SHA1 as cfae5c9a6fba3abf2252a98e16ee9b18bcca5371?
Do you have any idea, how I could check the compression method used here?

**Comment by MrKev312** [comment]
Mine is `00C4450A7F4BF76C74F6CBF37A750B918749AF1F`, taken from JD2019 (CUSA12549). Afaik the PS4 doesn't have region locking, so I'm leaning very much toward some small file corruption. I highly recommend re-dumping the game and using the latest version of [ShadPS4Plus](https://github.com/AzaharPlus/shadPS4Plus/releases) as there was an issue in 1.0 with games larger than 2 GB.
